# Generated by Django 4.2.2 on 2024-10-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_payments_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
    ]
