# Generated by Django 4.2.2 on 2024-10-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Введите название курса.', max_length=50, null=True, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью')),
                ('description', models.CharField(blank=True, help_text='Введите описание курса.', max_length=100, null=True, verbose_name='Описание курса')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Введите название урока.', max_length=50, null=True, verbose_name='Название урока')),
                ('description', models.CharField(blank=True, help_text='Введите описание урока.', max_length=100, null=True, verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью')),
                ('video_link', models.URLField(verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Курс')),
            ],
        ),
    ]
